### ISSUE TITLE
Pls add google drive support

### ISSUE THREAD

**Issue by VoQZHD** [duke7553/files-uwp#67] opened 2019-02-24 13:28 UTC

**Comment by fgff** [comment] 2019-02-24 13:59
That kind of nonsense? Why do I need this in Windows Explorer?

**Comment by VoQZHD** [comment] 2019-02-24 14:26
For examlle installed drive gives you trash sync, so if you clean it, it
will clean drive too. Also better file managment so. I think thats not hard
to you so pls add.

вс, 24 февр. 2019 г., 19:59 Ivan <notifications@github.com>:

**Comment by carlosrfernandez** [comment] 2019-02-25 14:42
Not sure I understand what the issue is? 

I've installed Google Drive File Stream on my system (which you need anyway, in order to sync), and the drive correctly shows up on the side bar. 

So again, I don't see what the problem is? See the image below, drive G:\ is google drive.

![image](https://user-images.githubusercontent.com/4179550/53344803-df98b680-3913-11e9-8cad-a8f454e8c566.png)

**Comment by PoorPocketsMcNewHold** [comment] 2019-02-25 14:47
@carlosrfernandez I suppose he want it be directly embedded in, a bit as Onedrive is for the classical file explorer. But since it's supports it flawlessly as an external drive, i have no need of having it supported more and close the issue.

**Comment by VoQZHD** [comment] 2019-02-25 15:56
Thx

пн, 25 февр. 2019 г., 20:48 PoorPockets McNewHold <notifications@github.com

**Closed** 2019-02-25 21:30 UTC

**Comment by yaira2** [comment] 2023-09-13 18:00
Support for Google Drive is now available. You can download the latest version of Files from our website https://files.community/download
