### ISSUE TITLE
Crash When Using a Removable Drive

### ISSUE THREAD

**Issue by Reset12138** [duke7553/files-uwp#103] opened 2019-05-18 14:29 UTC
It crashed when I opened a removable drive.
Surface Go
Windows 10 18362.86

>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() + 0x21
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task) + 0x70
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task) + 0x38
>    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task) + 0x17
>    at Files.Filesystem.ItemViewModel`1.<AddFolder>d__34.MoveNext() + 0xf8
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() + 0x21
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task) + 0x70
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task) + 0x38
>    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task) + 0x17
>    at System.Runtime.CompilerServices.TaskAwaiter.GetResult() + 0xb
>    at Files.Filesystem.ItemViewModel`1.<AddItemsToCollectionAsync>d__32.MoveNext() + 0xe33
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() + 0x21
>    at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__7_0(Object) + 0x1e
>    at System.Action`1.Invoke(T) + 0x28
>    at System.Threading.WinRTSynchronizationContext.Invoker.InvokeCore() + 0x33

**Comment by duke7553** [comment] 2019-05-18 14:34
Was there any other error information included with this?

**Comment by Reset12138** [comment] 2019-05-18 14:53
> @Reset12138
> 
> Was there any other error information included with this?
> What drive were you attempting to access?
> Is this the latest version of Files?
> Were you able to open the drive after re-opening the app?

- That's all the "Technical Information".
- WD My Passport Ultra 2TB
- Yes I'm using the latest version of Files.
- I can open the drive later and that kind of crash only happened once.

Just now I opened the Files then it crashed immediately, before I can see UI of the app.

> Summary:
> Unspecified error (Exception from HRESULT: 0x80004005)
> Technical Information:
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() + 0x21
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task) + 0x70
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task) + 0x38
>    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task) + 0x17
>    at Files.YourHome.<PopulateRecentsList>d__23.MoveNext() + 0xdf2
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() + 0x21
>    at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__7_0(Object) + 0x1e
>    at System.Action`1.Invoke(T) + 0x28
>    at System.Threading.WinRTSynchronizationContext.Invoker.InvokeCore() + 0x33

**Comment by duke7553** [comment] 2019-05-18 14:57
I would try re-installing the app because it looks like the app has become corrupted. If you can still reproduce the issue after doing the reinstall, then I'll look into it.

**Comment by Reset12138** [comment] 2019-05-18 15:09
I just re-install the app.
I tried to open the removable drive and this occured.
![批注 2019-05-18 230837](https://user-images.githubusercontent.com/40438607/57971530-e50d1680-79c1-11e9-8893-d40dfad30c1b.jpg)

**Comment by Reset12138** [comment] 2019-05-18 15:11
I removed the drive from computer and reopened the app. It crashed anyway.
![批注 2019-05-18 231103](https://user-images.githubusercontent.com/40438607/57971556-3cab8200-79c2-11e9-832f-7d40b6146beb.jpg)

**Comment by duke7553** [comment] 2019-05-18 18:54
@Reset12138 Did this drive work before the recent v0.5.0 updates?

**Comment by duke7553** [comment] 2019-05-21 20:48
@Reset12138 Okay, I made some changes in the newly-released snapshot 2. Please let me know whether they affect this bug.

**Comment by duke7553** [comment] 2019-05-28 00:02
I'll close this now, but please reopen if you can reproduce on the latest snapshots.

**Closed by duke7553** 2019-05-28 00:02 UTC
Labels: bug, high-priority
