### ISSUE TITLE
Crash on Startup

### ISSUE THREAD

**Issue by Crocodile73** [duke7553/files-uwp#410] opened 2020-02-13 12:58 UTC
Side loaded new 0.7 running Windows 1909 x64. Loads Files Beta screen, then shuts down. Clean install still the same.

**Comment by yaichenbaum** [comment] 2020-02-13 14:14
Do you have any additional drives attached to your device?

**Comment by Crocodile73** [comment] 2020-02-13 14:38
> Do you have any additional drives attached to your device?

i do yes

**Comment by yaichenbaum** [comment] 2020-02-13 14:39
@Crocodile73 To test if that is where the bug is can you try removing them and starting Files UWP again?

**Comment by Crocodile73** [comment] 2020-02-13 14:43
> @Crocodile73 To test if that is where the bug is can you try removing them and starting Files UWP again?

yes that is the issue. Its starts fine without them.

**Comment by yaichenbaum** [comment] 2020-02-13 14:44
Thank you for testing, I am marking this as a critical bug. This is something we will look in to as soon as possible.

**Comment by duke7553** [comment] 2020-02-13 20:33
@Crocodile73 Thank you for reporting this. Are these additional storage devices external or internal drives?

**Comment by yaichenbaum** [comment] 2020-02-13 20:34
@duke7553 I have seen this issue when connecting my phone to my laptop.

**Comment by Crocodile73** [comment] 2020-02-13 21:16
> @Crocodile73 Thank you for reporting this. Are these additional storage devices external or internal drives?

they are external USB

**Comment by Jviix** [comment] 2020-02-13 21:44
i have this issue without any external drives

**Comment by WinObs** [comment] 2020-02-14 18:27
I am curious if this would apply to mapped network drives? I just sideloaded the latest release on 1909 x64 and am crashing after the splash screen.

**Comment by generalguy41** [comment] 2020-02-14 21:10
@WinObs That's what I thought initially as my main PC at home is mapped to a network drive, but I just tested it on my Surface which has the same drive mapped and it loaded there.

**Comment by WinObs** [comment] 2020-02-14 21:31
Thanks @generalguy41 - I am trying on my main desktop with mapped drives - will give it a shot on my Surface Laptop (3) and see if it works. Thanks.

**Comment by duke7553** [comment] 2020-02-19 20:39
Unfortunately, I cannot repro this with my hardware. Since we know it exists, can someone checkout the develop branch and provide us debug info?

**Comment by Crocodile73** [comment] 2020-02-25 10:44
> Unfortunately, I cannot repro this with my hardware. Since we know it exists, can someone checkout the develop branch and provide us debug info?

sorry been away, what debug do you need, only side loaded the app.

**Comment by lampenlampen** [comment] 2020-02-25 11:15
does the crash still happen, if you grant the permission "BroadFileSystemAccess":

Win+R, `ms-settings:privacy-broadfilesystemaccess`.

**Comment by Crocodile73** [comment] 2020-02-25 11:54
> does the crash still happen, if you grant the permission "BroadFileSystemAccess":
> 
> Win+R, `ms-settings:privacy-broadfilesystemaccess`.

yes it still crashes, i had it on anyway.

**Comment by WinObs** [comment] 2020-02-25 14:19
On my system the overall setting was on but the app itself was not so I toggled it on.

Tried before rebooting and it still crashed. Rebooted and tried again – still crashing.

Rich

**Comment by Crocodile73** [comment] 2020-02-25 17:16
ok trial and error has lead me to a drive, which is a Samsung SSD Usb 3.0 250gb. This is the issue on my system. But i have checked the drive with all kinds of checks, and its fine, works great and has been plugged in for over 2 years. The odd thing is i have two plugged in, and the other one works connected. Hope this helps

**Comment by Crocodile73** [comment] 2020-02-25 17:16
ok trial and error has lead me to a drive, which is a Samsung SSD Usb 3.0 250gb. This is the issue on my system. But i have checked the drive with all kinds of checks, and its fine, works great and has been plugged in for over 2 years. The odd thing is i have two plugged in, and the other one works connected. Hope this helps

**Comment by duke7553** [comment] 2020-02-25 20:52
@Crocodile73 We just need you to clone the master branch and run in a debugger to find out what code causes this issue. (and the output)

Thanks a lot!

**Comment by Crocodile73** [comment] 2020-02-26 17:57
@duke7553 

Log Name:      Application
Source:        Application Error
Date:          26/02/2020 17:53:16
Event ID:      1000
Task Category: (100)
Level:         Error
Keywords:      Classic
User:          N/A
Computer:      DESKTOP-F3QESHP
Description:
Faulting application name: Files.exe, version: 1.0.0.0, time stamp: 0x5d36223e
Faulting module name: twinapi.appcore.dll, version: 10.0.18362.592, time stamp: 0x125d2980
Exception code: 0xc000027b
Fault offset: 0x00000000000d5cb8
Faulting process ID: 0xd54
Faulting application start time: 0x01d5eccd9be257ae
Faulting application path: C:\Program Files\WindowsApps\49306atecsolution.FilesUWP_0.7.0.0_x64__et10x9a9vyk8t\Files.exe
Faulting module path: C:\Windows\System32\twinapi.appcore.dll
Report ID: 3ba66927-5803-4568-8b7c-195b8000170a
Faulting package full name: 49306atecsolution.FilesUWP_0.7.0.0_x64__et10x9a9vyk8t
Faulting package-relative application ID: App

**Comment by yaichenbaum** [comment] 2020-03-03 17:42
Is anyone able to run Files from the source code to get more detailed information on what's causing the crash?

**Comment by lampenlampen** [comment] 2020-03-03 22:13
Can you create a branch for this issue? Then i will backport the logger to v0.7 and you can create a package, so we can get the stacktrace.

**Comment by duke7553** [comment] 2020-03-03 22:13
Does this bug affect any users on 20H1 or higher?

**Comment by yaichenbaum** [comment] 2020-03-03 22:14
@lampenlampen Just target the `develop` branch.

**Comment by lampenlampen** [comment] 2020-03-03 22:16
This branch already contains the logger. Can you create a package and link it here?
The affected users can then install it and upload the `debug.txt`, so we get a crash report.

**Comment by yaichenbaum** [comment] 2020-03-04 00:14
[Files.Package_0.7.0.0_x64_Debug.msixbundle.zip](https://github.com/duke7553/files-uwp/files/4284305/Files.Package_0.7.0.0_x64_Debug.msixbundle.zip)

**Comment by Crocodile73** [comment] 2020-03-04 13:06
> 
> 
> Does this bug affect any users on 20H1 or higher?

no 19H2 for me.

**Comment by Crocodile73** [comment] 2020-03-04 13:17
> 
> 
> This branch already contains the logger. Can you create a package and link it here?
> The affected users can then install it and upload the `debug.txt`, so we get a crash report.

does this have to be used with a debug tool?

**Comment by lampenlampen** [comment] 2020-03-04 13:57
No,
go to the folder `%localappdata%`, `Packages`, search there for the folder `Files` and there in the folder `LocalState` should be a file `debug.txt`, which contains a stacktrace.

**Comment by Jviix** [comment] 2020-03-04 14:51
Debug from yaichenbaum file:
2020-03-04 15:46:43.7966|INFO|Files.App|App launched
2020-03-04 15:46:43.8258|ERROR|Files.App|Acceso denegado. (Exception from HRESULT: 0x80070005 (E_ACCESSDENIED))

Acceso denegado = denied access

Files UWP has permission in file system, so... that's it

**Comment by yaichenbaum** [comment] 2020-03-04 14:53
@Jviix Hf you give file permission access does it resolve the issue?

**Comment by Crocodile73** [comment] 2020-03-04 14:55
same info as @Jviix 

2020-03-04 13:13:22.3586|ERROR|Files.App|Access is denied. (Exception from HRESULT: 0x80070005 (E_ACCESSDENIED))

**Comment by Jviix** [comment] 2020-03-04 14:55
Nope. Same issue. Tried 3 times.

**Comment by yaichenbaum** [comment] 2020-03-04 14:58
This is interesting, is anyone able to run from the source code? That should give us more information.

**Comment by Jviix** [comment] 2020-03-04 15:00
How can I run from source code? I'll do it

**Comment by yaichenbaum** [comment] 2020-03-04 15:01
https://github.com/duke7553/files-uwp/tree/develop#building-files-uwp-from-the-source-code

**Comment by Jviix** [comment] 2020-03-04 15:02
Thank you, downloading. I'll update asap.

**Comment by yaichenbaum** [comment] 2020-03-04 15:04
@Jviix Thank you so much, doing this will go a long way towards resolving this issue.

**Comment by yaichenbaum** [comment] 2020-03-04 15:55
@Jviix Try again using the `develop` branch.

**Comment by lampenlampen** [comment] 2020-03-04 16:02
@Jviix simple delete the certificates. They are still linked in VS, but the certificate file is not stored on git.

**Comment by lampenlampen** [comment] 2020-03-04 16:10
@yaichenbaum 
They are still referenced:
https://github.com/duke7553/files-uwp/blob/016c05dd54157b1de03ec1f02a74bc658ede7d06/Files.Package/Files.Package.wapproj#L155-L158

**Comment by yaichenbaum** [comment] 2020-03-04 16:12
@lampenlampen I am pretty sure that is fine, the main thing is that I removed the fingerprint from the `Package.wapproj` file.

**Comment by lampenlampen** [comment] 2020-03-04 16:15
@yaichenbaum You are right 👍

**Comment by Jviix** [comment] 2020-03-04 17:42
Well. After some time, I get this:

2020-03-04 18:42:07.8014|INFO|Files.Filesystem.DrivesManager|Drive added: C:\, Fixed
2020-03-04 18:42:07.8504|INFO|Files.Filesystem.DrivesManager|Drive added: D:\, Fixed
2020-03-04 18:42:08.0209|INFO|Files.App|App launched
2020-03-04 18:42:08.0339|ERROR|Files.App|Acceso denegado. (Exception from HRESULT: 0x80070005)

**Comment by lampenlampen** [comment] 2020-03-04 17:48
Do you have some other drives than the `C` and the `D` one.

**Comment by Jviix** [comment] 2020-03-04 17:48
Nope. Just C and D.

**Comment by yaichenbaum** [comment] 2020-03-04 17:50
@Jviix Were you able to build from the source code?

**Comment by Jviix** [comment] 2020-03-04 17:54
Yup. That log is from source code.

**Comment by Crocodile73** [comment] 2020-03-04 18:02
"type": "startService"
}Š “ycrashes{
  "exception": {
    "type": "System.UnauthorizedAccessException",
    "message": "Access is denied. (Exception from HRESULT: 0x80070005 (E_ACCESSDENIED))",
    "stackTrace": "   at Windows.Devices.Portable.StorageDevice.FromId(String deviceId)\r\n   at Files.Filesystem.DrivesManager.DeviceAdded(DeviceWatcher sender, DeviceInformation args)\r\n   at Windows.ApplicationModel.Core.UnhandledError.Propagate()\r\n   at Microsoft.AppCenter.Utils.ApplicationLifecycleHelper.<.ctor>b__17_1(Object sender, UnhandledErrorDetectedEventArgs eventArgs)"

**Comment by lampenlampen** [comment] 2020-03-04 19:48
@Crocodile73 Can you insert a breakpoint in line 78 in the `Drives.cs`-file and rerun the app?
I woulb be interested in the `tag` property of the `root`-variable.
And in which line is the exception thrown?

To prevent this error, we could simply catch this exception and skip this drive, but i think it would be good to know, why exactly it fails.

**Comment by lampenlampen** [comment] 2020-03-04 19:56
1. Is there anything special about the drive?
2. BitLocker?
3. Are you an admin?
4. Can you repro this behavior on another pc with this drive?

**Comment by Crocodile73** [comment] 2020-03-04 20:00
i haven't created from source file, i have just trialled and error-ed myself from the info in the directory. The drive is a SSD, I am going to run in another pc, and see what happens. The drive is error free, and has ran in previous builds.

**Comment by lampenlampen** [comment] 2020-03-04 20:02
@Jviix Are you sure that you don't have some other removable drive plugged in?
Assuming you and @Crocodile73 have the same error:
The crash happens in the `DeviceAdded`-method. This method is called by windows, if a removable storage device is added to the computer.

**Comment by lampenlampen** [comment] 2020-03-04 20:07
@Crocodile73 It's an external drive?

**Comment by Crocodile73** [comment] 2020-03-04 20:07
@lampenlampen yes it is

**Comment by lampenlampen** [comment] 2020-03-04 20:07
@Crocodile73 Which letter does the drive has?

**Comment by lampenlampen** [comment] 2020-03-04 20:10
@Crocodile73 Did it work in v0.6.6?

**Comment by Crocodile73** [comment] 2020-03-04 20:11
@lampenlampen it did yes

**Comment by lampenlampen** [comment] 2020-03-04 20:26
Can you open a shell in the root directory of your drive and start Files with `files.exe`?
UWP apps have automatically file-system permissions of the directory (and downwards) they are launched from in the shell.

**Comment by Crocodile73** [comment] 2020-03-04 20:38
@lampenlampen drive does the same on another PC. If i run files from a root directly it crashes still.

**Comment by duke7553** [comment] 2020-03-04 21:13
FYI: There may be a fix for this in the develop branch. Please try it out and let us know.

**Comment by duke7553** [comment] 2020-03-04 22:57
@lampenlampen @Crocodile73 I'll have a debug package prepared soon with some other fixes. If you want to try it out earlier, the potential fix is now in develop branch.

**Comment by Crocodile73** [comment] 2020-03-05 12:30
> @lampenlampen @Crocodile73 I'll have a debug package prepared soon with some other fixes. If you want to try it out earlier, the potential fix is now in develop branch.

build from source via the develop branch and it still crashes, unplugged the drive and checked build its 0.7.1.0

**Comment by duke7553** [comment] 2020-03-05 20:59
@Crocodile73 Can you run the app from Visual Studio (debug) and let us know what line it breaks on? This would really help me figure out what the issue is.

**Comment by Crocodile73** [comment] 2020-03-05 21:09
@duke7553 I don't know if i have done it right but says stack trace line 14

**Comment by duke7553** [comment] 2020-03-05 21:16
Which file?

**Comment by duke7553** [comment] 2020-03-05 21:16
@Crocodile73 Visual Studio should highlight a line inside a specific file

**Comment by duke7553** [comment] 2020-03-05 21:18
Could you give me the stack trace then?

**Comment by Crocodile73** [comment] 2020-03-05 21:19
can you give me a brief how too.

**Comment by duke7553** [comment] 2020-03-05 21:20
Step One: Launch the app from Visual Studio in debug mode
Step Two: Wait for an exception to be displayed. It should highlight a line number.

**Comment by duke7553** [comment] 2020-03-05 21:22
![image](https://user-images.githubusercontent.com/20365014/76026743-62782800-5efd-11ea-9bb6-093cc3e24229.png)
You'll see something like this. Just tell me what .cs file is open or send a screenshot.

**Comment by Crocodile73** [comment] 2020-03-05 21:24
loaded .sin file in. top says debug x64 files.launcher?

**Comment by KaKi87** [comment] 2020-03-05 21:29
I'm experiencing the same issue.

Here are screenshots of AOMEI Partition Assistant showing the external drive's properties :

![2020-03-05 22_26_10-AOMEI Partition Assistant Technician Edition](https://user-images.githubusercontent.com/21284089/76027302-b18b8080-5f30-11ea-8bb7-134b27a96b75.png)
![2020-03-05 22_26_41-AOMEI Partition Assistant Technician Edition](https://user-images.githubusercontent.com/21284089/76027300-b0f2ea00-5f30-11ea-87f4-2afb2f52856e.png)
![2020-03-05 22_27_26-AOMEI Partition Assistant Technician Edition](https://user-images.githubusercontent.com/21284089/76027296-afc1bd00-5f30-11ea-91cb-7b39136959eb.png)

Thanks

**Comment by KaKi87** [comment] 2020-03-05 21:37
I'm also experiencing a crash when this appears :

![2020-03-05 22_33_51-Greenshot](https://user-images.githubusercontent.com/21284089/76027912-c3b9ee80-5f31-11ea-9bc4-3c3b046f0520.png)

Clicking on the `Grant Permission` button doesn't do anything.

**Comment by duke7553** [comment] 2020-03-05 22:07
@KaKi87 Please verify you're running the latest code from develop, because that is what this issue is tracking. I'm pretty sure we fixed the second bug you're encountering in the develop branch.

**Comment by duke7553** [comment] 2020-03-05 23:51
@KaKi87 We're preparing a new APPX which should be ready soon.

**Comment by Crocodile73** [comment] 2020-03-06 10:41
what i got was:-

files.exe!files.view_Models.SettingsViewModel.LoadTerminalApps() Line 363

**Comment by duke7553** [comment] 2020-03-06 22:16
@Crocodile73 I added a change that should silently prevent loading the drives that are causing this problem. The app (develop branch) should now launch and log the drive ids which cannot be loaded.

**Comment by Crocodile73** [comment] 2020-03-07 09:56
@duke7553 That is working now.

**Comment by duke7553** [comment] 2020-03-07 18:04
@Crocodile73 Glad to hear you can use the app now.

**Closed** 2020-03-11 14:56 UTC
Labels: bug, fixed

**Comment by yaichenbaum** [comment] 2020-03-11 14:57
v0.7.1 is in the process of rolling out.
