### ISSUE TITLE
Additional Features Missing.

### ISSUE THREAD

**Issue by ashmanX** [duke7553/files-uwp#726] opened 2020-04-30 11:13 UTC
Hi, I would like you to add the following features in the upcoming releases:
1. Drag and Drop
2. Open With
3. Recycle Bin (alongside the Desktop option or somewhere)
THANK YOU

**Comment by xPoppyx** [comment] 2020-04-30 12:13
the app already supports drag and drop, the problem is that you must first select the file to be able to drag: #673

**Comment by yaichenbaum** [comment] 2020-04-30 12:25
@ashmanX Thank you for your feedback.
1. Drag and drop has already been implemented, make sure to update to the latest version (v0.7.8) in order to use this feature.
2. Open with is being tracked here #174 and there is already an open pull request #699.
3. Recycle bin is not yet supported but we are tracking a similar issue here #669.

I am going to be closing this issue since 1 has already been addressed and there are already open issues for the other ones. Make sure to subscribe to the relevant issues in order to get notified when they are addressed.

**Closed by yaichenbaum** 2020-04-30 12:25 UTC
Labels: enhancement, needs-triage
