### ISSUE TITLE
Add file extensions option

### ISSUE THREAD

**Issue by CrankySupertoon** [duke7553/files-uwp#235] opened 2019-09-17 21:07 UTC
Option to see the file extension. e.g .EXE instead of just for example chrome. it will be chrome.exe

**Comment by yaichenbaum** [comment] 2019-09-18 01:15
Duplicate of #225.

**Closed by yaichenbaum** 2019-09-18 01:15 UTC
Labels: enhancement

**Comment by yaira2** [comment] 2023-09-13 20:20
This feature is now available. You can download the latest version of Files from our website https://files.community/download
