### ISSUE TITLE
One Cosmetic Bug and One Feature Request

### ISSUE THREAD

**Issue by PeterStrick** [duke7553/files-uwp#760] opened 2020-05-09 14:41 UTC
**Describe the bug/feature**

[Bug]
When pressing on the OneDrive icon twice, the little blue indicator that shows, on what element of the sidebar you are currently on, moves to the Local Disc, where the OneDrive folder is physically stored in. It moves back to the OneDrive element of the sidebar when pressed on again.

[Feature request]
Add a option to change the icons in the sidebar. Like let the user choose from Icons from the system (like exe´s, dll´s, ico´s, ...) aswell as icons that already exist in Files UWP (like for example change the D drve icon to Files UWP´s OneDrive icon.)

**To Reproduce**

[Bug]
1. Open Files UWP
2. Click on OneDrive twice (OneDrive may need to be set up for this to work.)

**Expected behavior**
[Bug]
The blue indicator should stay on the OneDrive element and not jump to the local disc.

**Screenshots**
[Bug]
A screen capture in zip format is here: (146 KB when uncompressed)
[Screen Capture.zip](https://github.com/duke7553/files-uwp/files/4603711/Screen.Capture.zip)

**Desktop:**
 - OS Version: Windows 10 1909
 - App version: v0.8.0.0

**Additional context**
/

**Comment by yaichenbaum** [comment] 2020-05-10 02:50
Potential duplicate of #559.

**Comment by yaichenbaum** [comment] 2020-05-19 03:26
Thank you for opening this issue, we are going to move the tracking over to #559. Make sure to subscribe to the #559 to get notified when the issue is fixed.

**Closed by yaichenbaum** 2020-05-19 03:26 UTC
Labels: bug, needs-triage
