### ISSUE TITLE
Preview panel on the right like in explorer for pictures and audio and video

### ISSUE THREAD

**Issue by oddxends** [duke7553/files-uwp#234] opened 2019-09-17 18:29 UTC
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
Add any other context or screenshots about the feature request here. Ex: What device type/UI layout and app version?

**Comment by yaichenbaum** [comment] 2019-09-17 18:30
Duplicate of #130 Please subscribe to that issue for updates.

**Closed by yaichenbaum** 2019-09-17 18:30 UTC
Labels: duplicate, enhancement

**Comment by yaira2** [comment] 2023-09-13 20:20
Support for previewing files is now available. You can download the latest version of Files from our website https://files.community/download
