### ISSUE TITLE
Startup error message

### ISSUE THREAD

**Issue by LukasHrazdil** [duke7553/files-uwp#313] opened 2019-11-18 16:24 UTC
**Describe the bug**
When the app starts it shows the error message pasted in the section "Additional context". I can't open folders and the app is unusable.

**To Reproduce**

1. Go to "Start Menu"
2. Click on "Files UWP"

**Expected behavior**

The app should start normal.

**Screenshots**

![Unbenannt](https://user-images.githubusercontent.com/44154465/69069883-8a637e80-0a27-11ea-99df-b9cda4ad8dbc.png)

**Desktop**

 - OS: Windows 10 1903 18362.476
 - App version: v. 0.6.5.0

**Additional context**

Friendliy Description:
Zugriff verweigert (Exception from HRESULT: 0x80070005) within method (Method name unknown)

   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() + 0x21
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task) + 0x70
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task) + 0x38
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task) + 0x17
   at Files.App.<>c__DisplayClass7_0.<<PopulateDrivesListWithLocalDisks>b__3>d.MoveNext() + 0x11a
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() + 0x21
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__7_0(Object) + 0x1e
   at System.Action`1.Invoke(T) + 0x28
   at System.Threading.WinRTSynchronizationContext.Invoker.InvokeCore() + 0x33
   at System.Runtime.InteropServices.McgMarshal.ThrowOnExternalCallFailed(Int32, RuntimeTypeHandle) + 0x21
   at __Interop.ComCallHelpers.Call(__ComObject, RuntimeTypeHandle, Int32) + 0xb8
   at __Interop.ForwardComStubs.Stub_12[TThis](__ComObject, Int32) + 0x24
   at Microsoft.AppCenter.Utils.ApplicationLifecycleHelper.<.ctor>b__17_1(Object, UnhandledErrorDetectedEventArgs) + 0x3d
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() + 0x21
   at Microsoft.AppCenter.Utils.ApplicationLifecycleHelper.<.ctor>b__17_1(Object, UnhandledErrorDetectedEventArgs) + 0x75
   at System.EventHandler`1.Invoke(Object, TEventArgs) + 0x2e
   at __Interop.Intrinsics.HasThisCall__24[TArg0](Object, IntPtr, Object, TArg0) + 0x36
   at Files!<BaseAddress>+0xec2150

**Comment by yaichenbaum** [comment] 2019-11-18 16:38
Can you try updating to the latest version (0.6.6.0) and let us know if you still run in to the issue?

**Comment by duke7553** [comment] 2019-11-21 04:50
Closing this issue since it was likely fixed in v0.6.6 . @LukasHrazdil Can you please reopen if you can reproduce this after updating to the latest version?

**Closed by duke7553** 2019-11-21 04:50 UTC
Labels: bug, triage needed
