### ISSUE TITLE
Properties dialog

### ISSUE THREAD

**Issue by R3voA3** [duke7553/files-uwp#458] opened 2020-03-14 12:03 UTC
![image](https://user-images.githubusercontent.com/17484252/76681482-8a4d4700-65f3-11ea-8962-f703cfbcb9ed.png)

- Cancel button doesn't have rounded corners (Seems to be a style issue, all cancel buttons miss those)
- Icon is blurred
- Item Name property is missing the colon, but it's also incorrectly used.
- Last changed property uses an incorrect string (RecentItemClearAll.Text)
- Size and path properties are interchanged

*Seems like all the localisations are interchanged. 
PropertiesModified.Text is used instead of PropertiesItemType.Text
PropertiesItemSize.Text is used instead of PropertiesItemPath.Text

and so on and so forth

**Comment by yaichenbaum** [comment] 2020-03-15 02:15
1. This is an issue with the WinUI library and will be fixed whenever it is fixed on the WinUI end.
2. This should be easy enough to fix.

I think the other issues are all caused by localization issues, the strange thing is that we haven't done any work with localization in the properties dialog. I am wondering if that is automatically done by Windows...

**Comment by R3voA3** [comment] 2020-03-15 08:58
I see, that's why I couldn't find the cause of this in the properties dialog's xaml.

**Comment by yaichenbaum** [comment] 2020-03-15 13:34
@R3voA3 I am keeping this issue open until we fix the blurry icon. Even though the localization issue seems to be a Windows problem, we should still find a workaround so that's another reason to keep this issue open.

**Comment by R3voA3** [comment] 2020-03-21 00:05
This seems to be fixed except for the blurry icon.

**Comment by duke7553** [comment] 2020-04-06 16:54
Some work was done on this in v0.7.4, and the two issues you described may be fixed.

**Comment by duke7553** [comment] 2020-04-08 02:47
![image](https://user-images.githubusercontent.com/20365014/78739201-bf626600-7921-11ea-9908-eaa12ba1df41.png)

**Comment by R3voA3** [comment] 2020-04-08 09:16
Perfect

**Comment by yaichenbaum** [comment] 2020-04-12 02:14
@R3voA3 v0.7.4 has been released to the store, can you let us know if any of the issues you mentioned are still around?

**Comment by R3voA3** [comment] 2020-04-12 07:12
Issues have been fixed. Good work!

**Closed** 2020-04-12 14:12 UTC
Labels: bug, triage approved
