### ISSUE TITLE
Clicking twice on a folder/drive in the sidebar, the app closes

### ISSUE THREAD

**Issue by xPoppyx** [duke7553/files-uwp#422] opened 2020-02-20 11:57 UTC
if you are already inside the folder or drive and click again on it, the app closes, after several attempts, this happens 100% of the time.

Files uwp v0.7.0
W10 1909

**Comment by yaichenbaum** [comment] 2020-02-20 14:50
I am not able to reproduce this issue on my end, would you be able to run from the `develop` branch to get me more debug information?

**Comment by R3voA3** [comment] 2020-03-13 09:50
For me it doesn't crash, but it automatically opens the OneDrive.

**Comment by yaichenbaum** [comment] 2020-03-13 15:05
@R3voA3 We are tracking that issue here #418.

**Comment by duke7553** [comment] 2020-03-19 17:09
I can't repro this with the changes in develop,

**Comment by yaichenbaum** [comment] 2020-03-20 19:12
This should be fixed with the [v0.7.2](https://github.com/duke7553/files-uwp/releases/tag/v0.7.2) release, which is currently in certification in the Microsoft Store.

**Closed by yaichenbaum** 2020-03-20 19:12 UTC
Labels: bug, fixed
