### ISSUE TITLE
Add support for shortcut files

### ISSUE THREAD

**Issue by tomyan112** [duke7553/files-uwp#328] opened 2019-12-04 06:56 UTC
A shortcut file can be viewed in classic explorer but cant been seen in the files uwp.

![image](https://user-images.githubusercontent.com/9064351/70119773-fdb2f480-16a5-11ea-9b61-ef42fd0a7a8a.png)

**Comment by yaichenbaum** [comment] 2019-12-04 14:03
Possible duplicate of #2.

**Comment by duke7553** [comment] 2019-12-18 17:46
Hello, with our current implementation, this behavior is intended, but we're looking to improve this in the future when we add support for hidden items.

**Comment by duke7553** [comment] 2020-05-04 02:10
Moving this to #177

**Closed by duke7553** 2020-05-04 02:10 UTC
Labels: enhancement
