### ISSUE TITLE
Files UWP Crashed during tap and hold

### ISSUE THREAD

**Issue by Scubadog2008** [duke7553/files-uwp#201] opened 2019-08-01 19:22 UTC
I was expecting to be able to press-and-hold a file to bring up a context menu to allow me to copy, cut, delete, etc. the file.  Instead, it crashed.

**Comment by duke7553** [comment] 2019-08-01 19:23
Duplicate of https://github.com/duke7553/files-uwp/issues/159

**Closed by duke7553** 2019-08-01 19:23 UTC
