### ISSUE TITLE
Occasional error when copying Path

### ISSUE THREAD

**Issue by SOI7** [duke7553/files-uwp#332] opened 2019-12-07 19:06 UTC
When clicking on "Copy Path" on the ribbon, the app can occasionally give an error. It doesn't always happen but you can reproduce it spamming the button multiple times

OpenClipboard Failed (Exception from HRESULT: 0x800401D0) within method (Method name unknown)

 at System.Runtime.InteropServices.McgMarshal.ThrowOnExternalCallFailed(Int32, RuntimeTypeHandle) + 0x21
   at __Interop.ComCallHelpers.Call(__ComObject, RuntimeTypeHandle, Int32) + 0xb8
   at __Interop.ForwardComStubs.Stub_12[TThis](__ComObject, Int32) + 0x24
   at Files.Interacts.Interaction.GetPath_Click(Object, RoutedEventArgs) + 0x15a
   at Files.ProHome.CopyPathButton_Click(Object, RoutedEventArgs) + 0x95
   at Windows.UI.Xaml.Controls.SelectionChangedEventHandler.Invoke(Object, SelectionChangedEventArgs) + 0x2e
   at __Interop.Intrinsics.HasThisCall__24[TArg0](Object, IntPtr, Object, TArg0) + 0x36
   at Files!<BaseAddress>+0xec51e0
   at System.Runtime.InteropServices.McgMarshal.ThrowOnExternalCallFailed(Int32, RuntimeTypeHandle) + 0x21
   at __Interop.ComCallHelpers.Call(__ComObject, RuntimeTypeHandle, Int32) + 0xb8
   at __Interop.ForwardComStubs.Stub_12[TThis](__ComObject, Int32) + 0x24
   at Microsoft.AppCenter.Utils.ApplicationLifecycleHelper.<.ctor>b__17_1(Object, UnhandledErrorDetectedEventArgs) + 0x3d
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() + 0x21
   at Microsoft.AppCenter.Utils.ApplicationLifecycleHelper.<.ctor>b__17_1(Object, UnhandledErrorDetectedEventArgs) + 0x75
   at System.EventHandler`1.Invoke(Object, TEventArgs) + 0x2e
   at __Interop.Intrinsics.HasThisCall__24[TArg0](Object, IntPtr, Object, TArg0) + 0x36
   at Files!<BaseAddress>+0xec51e0

**Comment by yaichenbaum** [comment] 2019-12-17 15:52
I was able to reproduce this in v0.7.

**Comment by yaichenbaum** [comment] 2020-03-12 20:51
@SOI7 I am not able to reproduce this is v0.7.1, can you test if this is fixed on your end as well?

**Comment by SOI7** [comment] 2020-03-12 20:59
I'm not able to use Files atm because of #456

**Comment by yaichenbaum** [comment] 2020-03-20 19:12
This should be fixed with the [v0.7.2](https://github.com/duke7553/files-uwp/releases/tag/v0.7.2) release, which is currently in certification in the Microsoft Store.

**Closed by yaichenbaum** 2020-03-20 19:12 UTC
Labels: bug, triage approved
