### ISSUE TITLE
Wrong item selected after renaming file

### ISSUE THREAD

**Issue by Crummjyz** [duke7553/files-uwp#228] opened 2019-09-09 03:03 UTC
After renaming a file, the selection does not move to the file's new position. Instead, it remains in its place, e.g. second from the top.

**To Reproduce**
1. Select a file, and click 'Rename'
2. Enter a new name and press 'Set Name'
3. The wrong file is selected.

**Expected Behaviour**
After renaming, the selected file should not change. The selection should move to the file's new location.

**Screenshots**
_Before renaming, the file is second from top, and is selected._
![image](https://user-images.githubusercontent.com/30219746/64500625-12cfef80-d312-11e9-803c-d961b7d84bcb.png)

_After renaming, the file is at the bottom, but the selected file is still second from top._
![image](https://user-images.githubusercontent.com/30219746/64500687-4f035000-d312-11e9-9457-bba58b959ce0.png)

**Desktop:**
 - OS Version: Windows 10 1903 18362.295
 - App version: v0.6.2

**Additional context**
The issue does continue to occur after restarting the app.

**Comment by yaichenbaum** [comment] 2019-11-08 01:38
Duplicate of #211.

**Closed by yaichenbaum** 2019-11-08 01:38 UTC
Labels: bug
