### ISSUE TITLE
Add a right click option for classic file explorer

### ISSUE THREAD

**Issue by lorisobi** [duke7553/files-uwp#415] opened 2020-02-14 04:41 UTC
Maybe it would be nice to use, if there would be a right-click shortcut in normal file explorer to open the folder in Files UWP.

**Comment by yaichenbaum** [comment] 2020-02-16 05:39
In order to do this, we would need to modify the registry. We would like to stay away from doing that but if enough users are interested we can definitely reevaluate. I will keep this issue open for the time being in order to see if it picks up interest.

**Comment by szaimen** [comment] 2020-02-16 11:31
I think I would like it 👍

**Comment by d2dyno006** [comment] 2020-03-13 16:16
It would be great to see this feature! By such it would always remind you about the app

**Comment by lampenlampen** [comment] 2020-03-14 13:38
Scott Hanselman created a right click option for the windows terminal [link](https://github.com/shanselman/WindowsTerminalHere).

I think we could change the `inf`-file to our needs, but i have zero experience with this.

Maybe someone can have a look.

**Comment by yaichenbaum** [comment] 2020-03-15 20:15
This will launch Files UWP but not with the correct path. Feel free to play around and try to get it to do that.
```
; "Windows Terminal" PowerToy

[version]
signature="$CHICAGO$"

[FilesUWPHereInstall]
CopyFiles = FilesUWP.Files.Inf
AddReg    = FilesUWPHere.Reg

[DefaultInstall]
CopyFiles = FilesUWP.Files.Inf
AddReg    = FilesUWPHere.Reg

[DefaultUnInstall]
DelFiles  = FilesUWP.Files.Inf
DelReg    = FilesUWPHere.Reg

[SourceDisksNames]
55="Files UWP Here","",1

[SourceDisksFiles]
FilesUWPHere.INF=55

[DestinationDirs]
FilesUWP.Files.Inf = 17

[FilesUWP.Files.Inf]
FilesUWPHere.INF

[FilesUWPHere.Reg]
HKLM,%UDHERE%,DisplayName,,"%FilesUWPHereName%"
HKLM,%UDHERE%,UninstallString,,"rundll32.exe syssetup.dll,SetupInfObjectInstallAction DefaultUninstall 132 %17%\FilesUWPHere.INF"
HKCR,Directory\Shell\FilesUWPHere,,,"%FilesUWPHereAccel%"
HKCR,Directory\Shell\FilesUWPHere,Icon,,"%FilesUWPHereIcon%"
HKCR,Directory\Shell\FilesUWPHere\command,,0x00020000,""%%LOCALAPPDATA%%\Microsoft\WindowsApps\files.exe -d " ""%1"""
HKCR,Directory\Background\Shell\FilesUWPHere,,,"%FilesUWPHereAccel%"
HKCR,Directory\Background\Shell\FilesUWPHere,Icon,,"%FilesUWPHereIcon%"
HKCR,Directory\Background\Shell\FilesUWPHere\command,,0x00020000,""%%LOCALAPPDATA%%\Microsoft\WindowsApps\files.exe -d " ""%V"""
HKCR,Drive\Shell\FilesUWPHere,,,"%FilesUWPHereAccel%"
HKCR,Drive\Shell\FilesUWPHere,Icon,,"%FilesUWPHereIcon%"
HKCR,Drive\Shell\FilesUWPHere\command,,0x00020000,""%%LOCALAPPDATA%%\Microsoft\WindowsApps\files.exe -d " ""%1\"""

[Strings]
FilesUWPHereName="Files UWP Here PowerToy"
FilesUWPHereAccel="Open Files UWP Here"
UDHERE="Software\Microsoft\Windows\CurrentVersion\Uninstall\FilesUWPHere"
FilesUWPHereIcon=""%%LOCALAPPDATA%%\Microsoft\WindowsApps\files.exe",0"
```

**Comment by lampenlampen** [comment] 2020-03-17 18:42
The correct commandline argument for opening a folder is `-WorkingDirectory` and not `-d`.

**Comment by yaichenbaum** [comment] 2020-03-17 22:39
![image](https://user-images.githubusercontent.com/39923744/76908208-8123da80-687e-11ea-8835-22c3d44f81a7.png)

@lampenlampen That helped somewhat, the app is still not navigating to the right directory but it looks like we are closer than before.

**Comment by yaichenbaum** [comment] 2020-03-17 22:45
I got it working correctly.

```
; "Windows Terminal" PowerToy

[version]
signature="$CHICAGO$"

[FilesUWPHereInstall]
CopyFiles = FilesUWP.Files.Inf
AddReg    = FilesUWPHere.Reg

[DefaultInstall]
CopyFiles = FilesUWP.Files.Inf
AddReg    = FilesUWPHere.Reg

[DefaultUnInstall]
DelFiles  = FilesUWP.Files.Inf
DelReg    = FilesUWPHere.Reg

[SourceDisksNames]
55="Files UWP Here","",1

[SourceDisksFiles]
FilesUWPHere.INF=55

[DestinationDirs]
FilesUWP.Files.Inf = 17

[FilesUWP.Files.Inf]
FilesUWPHere.INF

[FilesUWPHere.Reg]
HKLM,%UDHERE%,DisplayName,,"%FilesUWPHereName%"
HKLM,%UDHERE%,UninstallString,,"rundll32.exe syssetup.dll,SetupInfObjectInstallAction DefaultUninstall 132 %17%\FilesUWPHere.INF"
HKCR,Directory\Shell\FilesUWPHere,,,"%FilesUWPHereAccel%"
HKCR,Directory\Shell\FilesUWPHere,Icon,,"%FilesUWPHereIcon%"
HKCR,Directory\Shell\FilesUWPHere\command,,0x00020000, %%LOCALAPPDATA%%\Microsoft\WindowsApps\files.exe -Directory ""%1""
HKCR,Directory\Background\Shell\FilesUWPHere,,,"%FilesUWPHereAccel%"
HKCR,Directory\Background\Shell\FilesUWPHere,Icon,,"%FilesUWPHereIcon%"
HKCR,Directory\Background\Shell\FilesUWPHere\command,,0x00020000, %%LOCALAPPDATA%%\Microsoft\WindowsApps\files.exe -Directory ""%V""
HKCR,Drive\Shell\FilesUWPHere,,,"%FilesUWPHereAccel%"
HKCR,Drive\Shell\FilesUWPHere,Icon,,"%FilesUWPHereIcon%"
HKCR,Drive\Shell\FilesUWPHere\command,,0x00020000, %%LOCALAPPDATA%%\Microsoft\WindowsApps\files.exe -Directory ""%1\""

[Strings]
FilesUWPHereName="Files UWP Here PowerToy"
FilesUWPHereAccel="Open Files UWP Here"
UDHERE="Software\Microsoft\Windows\CurrentVersion\Uninstall\FilesUWPHere"
FilesUWPHereIcon=""%%LOCALAPPDATA%%\Microsoft\WindowsApps\files.exe",0"
```

**Comment by lampenlampen** [comment] 2020-03-18 11:42
Yeah this is a bug in https://github.com/duke7553/files-uwp/blob/1f81dc3a1555d08afc5a3d18eb0deec0f6fbd729/Files/CommandLine/CommandLineParser.cs#L45

We must not split the whitespace, if it is in a sequence surrounded by quotation marks.

**Comment by yaichenbaum** [comment] 2020-03-18 15:09
Good to know the issue is not in the `inf` file.

**Comment by lampenlampen** [comment] 2020-03-27 16:46
I also found this repo:
https://github.com/kerol2r20/Windows-terminal-context-menu

It uses a powershell script instead of a inf file.

**Comment by yaichenbaum** [comment] 2020-03-27 17:58
I started adding pages to the Files UWP wiki, would you be interested in adding this to the page that explains how to use the inf file?

**Comment by yaichenbaum** [comment] 2020-04-05 15:38
@lorisobi I hope the `inf` file helps you. I am going to be closing this issue now, but feel free to open a new one if you have any other feedback.

**Closed by yaichenbaum** 2020-04-05 15:38 UTC
Labels: enhancement, triage needed
