### ISSUE TITLE
The refresh icon to the left of the address bar flickers every time a folder is refreshed or opened.

### ISSUE THREAD

**Issue by R3voA3** [duke7553/files-uwp#394] opened 2020-02-03 09:11 UTC
The refresh icon to the left of the address bar flickers every time a folder is refreshed or opened.

**Comment by yaichenbaum** [comment] 2020-02-03 14:13
@R3voA3 Thanks for creating this issue, I was able to reproduce the first two issues but I am not sure what you mean by "Something is wrong with the icons". Would you mind explaining what you meant by that?

**Comment by R3voA3** [comment] 2020-02-03 15:17
Check out the video and look at the icons. They change their appearance for a moment. Looks like some placeholder icons are first applied (Just a guess, haven't looked at the code)

**Comment by yaichenbaum** [comment] 2020-02-03 15:18
This is because we have improved the speed for loading files so much that they load faster then the thumbnails now.

**Comment by duke7553** [comment] 2020-02-03 20:52
@R3voA3 Thanks for bringing this to our attention.

**Comment by SOI7** [comment] 2020-02-03 21:33
You may also want to hide the first two folders named . and .. but you probably already know about that

**Comment by yaichenbaum** [comment] 2020-02-04 02:00
@SOI7 Yeah, we will do take care of that in the future. Unfortunately we haven't been able to ship any updates through the store since there is a bug in Visual Studio stopping us from creating release packages and we are waiting for them to fix it.

**Comment by yaichenbaum** [comment] 2020-02-16 05:53
@R3voA3 Can you let me know if this is still an issue with the latest release?

**Comment by R3voA3** [comment] 2020-02-16 09:23
@yair100 I would love to try it, but it won't let me install the version 7.0.0 due to a not trusted certificate, although I installed the certificate and also the debug dependency

Edit: Nevermind, I fixed it. The certificate needed to be installed in the folder "Authorities for installation of trusted packed apps" (Just a free translation)

The issue seems to be mostly fixed. Only the textBox with the path is still having that weird animation and .docx, .pdf and other file types have a placeholder icon now.

![image](https://user-images.githubusercontent.com/17484252/74602342-c00c1800-50a7-11ea-961d-ca4f16b25919.png)

**Comment by yaichenbaum** [comment] 2020-02-16 15:13
@R3voA3 if you wait a few seconds do the icons load?

**Comment by R3voA3** [comment] 2020-02-16 15:19
No they didn't @yair100

**Comment by yaichenbaum** [comment] 2020-02-16 15:20
Ok, thanks for letting me know.

**Comment by duke7553** [comment] 2020-02-17 20:27
@R3voA3 , if you resize the Window, do items load?

**Comment by R3voA3** [comment] 2020-02-18 00:26
They indeed do. @duke7553

**Comment by duke7553** [comment] 2020-02-19 20:28
@R3voA3 This should be fixed with the latest work in the develop branch.

**Comment by R3voA3** [comment] 2020-03-13 09:52
In the latest version 7.1.0, most of the animations have been fixed, except the refresh icon to the left of the adress bar. It flickers every time a folder is refreshed or opened.

**Comment by duke7553** [comment] 2020-03-13 19:28
@R3voA3 Hello. This is by design because we don't want users to spam the refresh button. (which would cause unexpected behavior)

**Comment by R3voA3** [comment] 2020-03-14 11:55
I can still spam it. I can also spam refresh by clicking at the folder quickly.

**Comment by yaichenbaum** [comment] 2020-03-15 02:12
You might be able to click on it a bunch of times, but it prevents you from clicking it too fast.

**Closed** 2020-03-20 22:15 UTC
Labels: bug, wontfix
